# Generated by Django 3.0.3 on 2020-07-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manhuainfo',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('com', models.CharField(max_length=1000)),
                ('new', models.CharField(max_length=255)),
                ('pop', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
