# Generated by Django 3.0.3 on 2020-07-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhuainfo',
            name='link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manhuainfo',
            name='pho',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
