# Generated by Django 3.0.3 on 2020-09-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql02', '0002_auto_20200729_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='maninfo',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
            ],
        ),
    ]
