# Generated by Django 3.0.3 on 2020-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql02', '0004_auto_20200923_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='登录用户')),
                ('ip', models.GenericIPAddressField(verbose_name='用户IP地址')),
                ('count', models.SmallIntegerField(verbose_name='登录次数')),
                ('lock', models.SmallIntegerField(verbose_name='锁')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '历史登录',
                'verbose_name_plural': '历史登录',
                'db_table': 'login_history',
            },
        ),
    ]
