# Generated by Django 3.0.3 on 2020-09-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql02', '0005_login_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_history',
        ),
    ]
