# Generated by Django 3.0.3 on 2020-09-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql02', '0006_delete_login_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='maninfo',
            name='on',
            field=models.IntegerField(default=0),
        ),
    ]
