# Generated by Django 3.0.3 on 2020-09-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql02', '0007_maninfo_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maninfo',
            name='usernum',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
